Anwendung/app/auftritt/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.utils.translation import gettext_lazy as _

# for generating a concise sitemap
# For more, please see: https://docs.djangoproject.com/en/4.1/ref/contrib/sitemaps/
from basic.sitemaps import StaticBasicMap
from blog.sitemaps import StaticBlogListMap, BlogSitemap
from contact.sitemaps import StaticContactMap

sitemaps = {
    'basic': StaticBasicMap,
    'blog_list' : StaticBlogListMap,
    'blog_entries': BlogSitemap,
    'contact' : StaticContactMap,
}

# Admin pages and sitemap paths
urlpatterns = [
    path(settings.ADMIN_URL + '/', admin.site.urls),
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
]

# Paths for all other
urlpatterns += i18n_patterns(
    path('', include('basic.urls'), name='basic'),
    path(_('kontakt/'), include('contact.urls'), name='contact'),
    path(_('blog/'), include('blog.urls'), name='blog'),
    prefix_default_language=False
)

# Paths for uploaded resources during development and debug
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

Anwendung/app/basic/urls.py
"""Submodule containing the paths for this app."""
from django.urls import path
from django.views.generic import TemplateView
from django.utils.translation import gettext_lazy as _

app_name = 'basic'
urlpatterns = [
    path('', TemplateView.as_view(template_name='basic/home.html'), name='home'),
    path(_('about/'), TemplateView.as_view(template_name='basic/about.html'), name='about'),
    path(_('imprint/'), TemplateView.as_view(template_name='basic/imprint.html'), name='imprint'),
    path(_('privacy/'), TemplateView.as_view(template_name='basic/privacy.html'), name='privacy'),
]

Anwendung/app/blog/urls.py
"""Submodule containing the paths for this app."""
from django.urls import path
from django.views.generic import ListView, DetailView
from .models import Entry

app_name = 'blog'
urlpatterns = [
    path(
        '',
        ListView.as_view(
            model=Entry,
            paginate_by=8,
        ),
        name='list'
    ),
    path(
        '<slug:slug>/',
        DetailView.as_view(
            model=Entry,
        ),
        name='entry'
    ),
]

Anwendung/app/contact/urls.py
"""Submodule containing the paths for this app."""
from django.urls import path, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, TemplateView
from .forms import ContactForm

app_name = 'contact'
urlpatterns = [
    path(
        '',
        CreateView.as_view(
            template_name='contact/contact_form.html',
            form_class=ContactForm,
            success_url=reverse_lazy('contact:sent'),
        ),
        name='form'
    ),
    path(
        _('sent/'),
        TemplateView.as_view(template_name='contact/contact_sent.html'),
        name='sent'
    ),
]

Anwendung/app/basic/templates/base.html
<!DOCTYPE html>
{% load i18n static %}{% get_current_language as LANGUAGE_CODE %}<html lang="{{ LANGUAGE_CODE }}">
    <head>
        <meta charset="utf-8">
        <meta name="author" content="Lorenz Zahn">
        <meta name="description" content="{% block description %}{% endblock %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="apple-touch-icon" sizes="180x180" href="/static/icon/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/static/icon/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/static/icon/favicon-16x16.png">
        <link rel="manifest" href="/static/icon/site.webmanifest">
        <link rel="mask-icon" href="/static/icon/safari-pinned-tab.svg" color="#5bbad5">
        <link rel="icon" type="image/svg+xml" href="/static/icon/favicon.svg" sizes="any">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">
        <link rel="stylesheet" type="text/css" href="/static/style.css">
        <script type="text/javascript" src="/static/menu.js" defer></script>
        <title>{% block title %}{% endblock %}</title>{% block head %}{% endblock %}
    </head>
    <body>
        <header>
            <div class="header-bar">
                <label id="menu-icon" for="menu-btn" tabindex="0" role="button">
                    <img class="hamburger-icon" src="/static/menu.svg" type="image/svg+xml" alt="{% translate "Menü" %}">
                </label>
            </div>
            <input class="menu-btn" type="checkbox" id="menu-btn">
            <nav id="header-nav">
                <ul>
                    <li><a href="{% url 'basic:home' %}">{% translate "Hauptseite" %}</a></li>
                    <li><a href="{% url 'basic:about' %}">{% translate "Über mich" %}</a></li>
                    <li><a href="{% url 'blog:list' %}">{% translate "Blog" %}</a></li>
                    <li><a href="{% url 'contact:form' %}">{% translate "Kontakt" %}</a></li>
                    <li><a href="{% url 'basic:imprint' %}">{% translate "Impressum" %}</a></li>
                    <li><a href="{% url 'basic:privacy' %}">{% translate "Datenschutz" %}</a></li>
                </ul>
            </nav>
        </header>
        <main>{% block main %}{% endblock %}</main>
    </body>
</html>